<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMUIuxUM\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMUIuxUM/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMUIuxUM.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMUIuxUM\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMUIuxUM\App_KernelDevDebugContainer([
    'container.build_hash' => 'MUIuxUM',
    'container.build_id' => 'fa73aaad',
    'container.build_time' => 1749902222,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMUIuxUM');
